workflows:
  my-workflow:
    name: My Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter packages get
      - name: Run tests
        script: |
          flutter test
      - name: Build APK
        script: |
          flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
