workflows:
  my-workflow:
    name: My Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter packages get
      - name: Build APK
        script: |
          flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - "phanukonelvk@gmail.com"
          - "teynajah@gmail.com"
        
